# Generated by Django 2.1.2 on 2018-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0002_vote_token_election_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='candidate_fname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='winner',
            name='candidate_lname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
